### ISSUE TITLE
Relase on F-Droid and release apk on github

### ISSUE THREAD

**Issue by qw123wh** [pranavkapoor001/Alarmzy#1]
I think that by making the app available on F-Droid too, it will be discovered and used by many more people.  At the moment only on the play store it is difficult to find your app if you do not know it, while on F-Droid it would have more visibility and consequently will be used by more users. If you also release the apk directly on github it wouldn't be a bad idea.  But the important thing is F-Droid only so your great app will be successful

**Comment by pranavkapoor001** [comment]
sure
